project:
  title: "Manuscript"
  output-dir: output

  render:
    - "manuscript.qmd"
    - "appendix.qmd"

format:
  # Nice HTML output
  html:
    toc: true
    include-in-header:
      - text: |
          <style type="text/css">
          h2.hide {
            display: none;
          }
          </style>
    language: 
      title-block-published: "Latest version"
    format-links:
      - html
      - format: hikmah-pdf
        text: PDF
        icon: file-pdf
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - html/custom.scss
    citeproc: false
    filters: 
      - at: pre-render
        path: "_extensions/wordcount/citeproc.lua"
      - at: pre-render
        path: "_extensions/wordcount/wordcount.lua"
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300


  # Nice PDF output
  hikmah-pdf:
    list-of-figures-normal: true

    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    sansfont: "Noto Sans"
    mathfont: "Libertinus Math"
    # linestretch: 1.05

    include-in-header:
      # The \everydisplay thing makes all math blocks use \small font
      text: |
        \usepackage{mathtools}
        \usepackage{tabularray}
        \usepackage{ragged2e}
        \justifying
        \everydisplay\expandafter{\the\everydisplay\small }
        \SetTblrStyle{foot}{font=\footnotesize}

        \NewTblrTheme{long}{
          \SetTblrStyle{caption}{hang=0pt}
          \SetTblrStyle{capcont}{hang=0pt}
          \SetTblrStyle{caption-tag}{font=\small\sffamily\bfseries}
          \SetTblrStyle{caption-text}{font=\small\sffamily}
          \SetTblrStyle{conthead-text}{font=\small\sffamily}
          \SetTblrStyle{contfoot}{font=\small\sffamily}
        }

    knitr:
      opts_chunk:
        dev: "cairo_pdf"


