---
title: "TITLE"
short-title: "Shortitle"
subtitle: "(Research note)"
author:
- name: A B
  affiliation: C
  orcid: 0000-0003-0000-0000
  url: a.bc
  email: d@e.fg
  attributes:
    corresponding: true
correspondence-prefix: "Correspondence concerning this article should be addressed to"
abstract: |
  {{< lipsum 1 >}}
thanks: |
  Mauruuru roa
date: 2024-12-13
code-repo: "Access the code, data, and analysis at <url>"
keywords:
  - A
  - B
  - C
bibliography: references.json
csl: csl/chicago-author-date.csl
link-citations: true
---

```{r setup, include=FALSE}
if (is.null(knitr::pandoc_to())) {
  fmt_out <- "interactive"
} else {
  fmt_out <- knitr::pandoc_to()
}

knitr::opts_chunk$set(echo = FALSE, include = FALSE, 
                      warning = FALSE, message = FALSE)

knitr::opts_chunk$set(fig.align = "center", fig.retina = 3,
                      fig.width = 6, fig.height = (6 * 0.618),
                      out.width = "80%", collapse = TRUE)

options(digits = 3, width = 120,
        dplyr.summarise.inform = FALSE,
        knitr.kable.NA = "")
```

```{r libraries-data}
library(tidyverse)
library(cowplot)
```


# Introduction

{{< lipsum 1 >}}

# Material and Methods
{{< lipsum 2 >}}


# Discussion

{{< lipsum 2 >}}
Blah. 
See @fig-label for a test.

```{r}
#| label: fig-label
#| fig-cap: "Figure Title"
#| fig-width: 6.5
#| fig-height: 2.5
#| out-width: "100%"
#| include: true
#| echo: false
ggplot(aes(x = speed, y = dist), data = cars)+
  geom_smooth(method = "lm", col = "darkred", fill = "pink")+
  geom_point(shape = 21, col = "white", fill = "darkblue")+
  theme_cowplot()
```

# Conclusion

{{< lipsum 1 >}}

# References

